using System;
using System.Windows.Forms;
using System.Data.Entity;

namespace RGroupTestApp1
{
    public partial class Form1 : Form
    {
        RGroupTestApp1.DqCyNPBxnfEntities dbContext = new RGroupTestApp1.DqCyNPBxnfEntities();

        public Form1()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext

            // Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
            dbContext.Items.LoadAsync().ContinueWith(loadTask =>
            {
                // Bind data to control when loading complete
                itemsBindingSource.DataSource = dbContext.Items.Local.ToBindingList();
            }, System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext());
        }

        private void gridView1_RowUpdated(object sender, DevExpress.XtraGrid.Views.Base.RowObjectEventArgs e)
        {
            dbContext.SaveChanges();
        }

        private void addButton_Click(object sender, EventArgs e)
        {
            gridView1.AddNewRow();
            gridView1.SetRowCellValue(gridView1.FocusedRowHandle, colName, "New Item");
            gridView1.SetRowCellValue(gridView1.FocusedRowHandle, colPrice, 0);
            gridView1.SetRowCellValue(gridView1.FocusedRowHandle, colQuantity, 0);
            gridView1.UpdateCurrentRow();
        }

        private void removeButton_Click(object sender, EventArgs e)
        {
            gridView1.DeleteRow(gridView1.FocusedRowHandle);
            dbContext.SaveChanges();
        }
    }
}
